server:
  port: 8887
spring:
  thymeleaf:
    cache: false
github:
  client_id: 747e745d933477ad3303
  client_secret: 761f21f1f9f675fe28c83e136801bb0f88a614ae
  redirect_uri: http://localhost:8887/callback